# Generated by Django 4.1.4 on 2022-12-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('name', models.CharField(max_length=128, null=True)),
                ('identifier', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"game"."card_type"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('info', models.TextField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('wisdom', models.IntegerField(null=True)),
                ('faith', models.IntegerField(null=True)),
                ('attack', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('alliance', models.CharField(max_length=64, null=True)),
                ('is_minion', models.BooleanField(null=True)),
            ],
            options={
                'db_table': '"game"."character"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': '"game"."character_class"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('instance', models.CharField(max_length=32, null=True)),
                ('attribute', models.CharField(max_length=32, null=True)),
                ('operation', models.CharField(max_length=4, null=True)),
                ('factor', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"game"."consequence"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('spiritual_intervention', models.BooleanField(null=True)),
                ('is_global', models.BooleanField(null=True)),
            ],
            options={
                'db_table': '"game"."event"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=64, null=True)),
                ('range', models.IntegerField(null=True)),
                ('rarity', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': '"game"."item"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('slate', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': '"game"."level"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nick_name', models.CharField(max_length=64, null=True)),
                ('ended', models.BooleanField(null=True)),
            ],
            options={
                'db_table': '"game"."match"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': '"game"."origin"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.CharField(max_length=64, null=True)),
                ('attribute', models.CharField(max_length=64, null=True)),
                ('required', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"game"."requirement"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('lives', models.IntegerField(null=True)),
                ('is_alive', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"game"."player.py"',
                'managed': True,
            },
        ),
    ]
