# Generated by Django 4.1.4 on 2022-12-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='consequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.consequence'),
        ),
        migrations.AddField(
            model_name='event',
            name='consequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.consequence'),
        ),
        migrations.AddField(
            model_name='event',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.requirement'),
        ),
        migrations.AddField(
            model_name='item',
            name='consequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.consequence'),
        ),
        migrations.AddField(
            model_name='level',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.character'),
        ),
        migrations.AddField(
            model_name='match',
            name='turn_of',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='consequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.consequence'),
        ),
        migrations.AddField(
            model_name='player',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.character'),
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.match'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.characterclass'),
        ),
    ]
