# Generated by Django 4.1.4 on 2022-12-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_characterclass_consequence_event_consequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"game"."bag"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField(null=True)),
                ('cover', models.IntegerField(null=True)),
                ('left_arm', models.IntegerField(null=True)),
                ('right_arm', models.IntegerField(null=True)),
                ('feet', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"game"."body"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='span',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.bag'),
        ),
        migrations.AddField(
            model_name='player',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.body'),
        ),
    ]
