# Generated by Django 4.1.4 on 2022-12-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_bag_body_item_span_player_bag_player_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(null=True)),
                ('column', models.CharField(max_length=1, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.item')),
                ('player.py', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.player.py')),
            ],
            options={
                'db_table': '"game"."cell"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.bag')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.item')),
            ],
            options={
                'db_table': '"game"."bag_item"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(null=True)),
                ('columns', models.IntegerField(null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.match')),
            ],
            options={
                'db_table': '"game"."arena"',
                'managed': True,
            },
        ),
    ]
